name: GitHub Pages
on:
    workflow_dispatch:
    push:
        branches:
            - main
            - dev
permissions:
    contents: write
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
defaults:
    run:
        working-directory: ./docs
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
              with:
                  submodules: "recursive"
                  fetch-depth: 10
            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version: "22"
                  cache: npm
            - run: npm ci
            - name: Build docs
              run: npm run build
            - name: No jekyll
              run: touch dist/.nojekyll
            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@920cbb300dcd3f0568dbc42700c61e2fd9e6139c # v4.6.4
              with:
                  folder: docs/dist
                  single-commit: true