name: build
on:
    pull_request:
        types: [ready_for_review, synchronize]
        branches:
            - main
            - dev
    workflow_dispatch:
concurrency:
    group: genai-test-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
permissions:
    models: read
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: install node
              run: npm ci
            - name: build genaiscript
              run: npm run build
            - name: run tests
              run: npm run test
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
