name: GenAI Issue Labeller
on:
    issues:
        types: [opened]
permissions:
    contents: read
    issues: write
    models: read
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    genai-issue-labeller:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
            - uses: pelikhan/action-genai-issue-labeller@5c4de86fb33380cb77688c7bfbf6cbec39b77fb7 # v0.0.37
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
