on:
    workflow_dispatch:
jobs:
    install_github_models:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: gh extension install https://github.com/github/gh-models
            - run: gh models --help
