name: genai pull request review
on:
    pull_request:
        types: [opened, ready_for_review, reopened]
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: "recursive"
                  fetch-depth: 10
            - name: git stuff
              run: git fetch origin && git pull origin main:main
            - name: genaiscript pr-describe
              run: npx --yes genaiscript run pr-describe --out ./temp/genai/pr-describe -prd --out-trace $GITHUB_STEP_SUMMARY
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  OPENAI_API_TYPE: ${{ secrets.OPENAI_API_TYPE }}
                  OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
            - name: genaiscript pr-review
              run: npx --yes genaiscript run pr-review --out ./temp/genai/pr-review -prc --out-trace $GITHUB_STEP_SUMMARY
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_COMMIT_SHA: ${{ github.event.pull_request.base.sha}}
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  OPENAI_API_TYPE: ${{ secrets.OPENAI_API_TYPE }}
                  OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
